author: PenguinMan
description: "Custom Fishing plugin"
main: me.Penguin.SuperFishing.Main
name: SuperFishing
version: 1.0.0
depend: [Vault]
api-version: 1.16

commands:

  fishing: 
    usage: /<command> [givecrate, reload]
    description: "Base SuperFishing Command"
    
  fishingshop:
    usage: /<command>
    aliases: [fs]
  
  fishtest:
    usage: /<command>


permissions: 
   
  superfishing.givecrate:
    default: op
    
#  a.a:
 #   default: op
  #  description: "a"
    